package hr.fer.oprpp1.hw02.prob1;

/**
 * Represents a token generated by the Lexer object.
 *
 * @author Ian Golob
 */
public class Token {

    private TokenType type;
    private Object value;

    public Token(TokenType type, Object value) {
        this.type = type;
        this.value = value;
    }

    public TokenType getType() {
        return type;
    }

    public Object getValue() {
        return value;
    }
}
