package hr.fer.oprpp1.custom.scripting.lexer;

/**
 * Represents a token generated by the Lexer object.
 *
 * @author Ian Golob
 */
public class Token {

    private final TokenType type;
    private final Object value;

    public Token(TokenType type, Object value) {
        this.type = type;
        this.value = value;
    }

    public TokenType getType() {
        return type;
    }

    public Object getValue() {
        return value;
    }

}
